version: '3.8'

services:
  postgres:
    image: postgres
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_management
    ports:
      - "5768:5432"  #Map host port 5768 to container port 5432
    networks:
      postgres-enabled-network:

  springboot-restful-webservices:
    build:
      context: ./
      dockerfile: Dockerfile
    image: springboot-restful-webservices
    container_name: my_restful_app
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      postgres-enabled-network:
    restart: on-failure


networks:
  postgres-enabled-network: