spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

rabbitmq:
  queue:
    name: "rbb_queue"
    json-name: "json_rbb_queue"
  exchange:
    name: "rbb_exchange"
  routing:
    key: "rbb_routing_key"
    json-key: "json_rbb_routing_key"
